# Generated by Django 4.2.11 on 2024-03-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('times_played', models.IntegerField(default=0)),
            ],
        ),
    ]
